import type { CardType } from './types';
import type { SiteCard } from './types';

const DEFAULT_IMAGE = '/cards_visuals/lotr_default.jpg';
const DEFAULT_GAMETEXT =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.';
/*
Formatted Text :
    \n => Return
    ** my text ** => bold
*/

export const FREE_PEOPLES_DATABASE: CardType[] = [
    {
        id: '2c102',
        title: 'Frodon',
        subtitle: 'Aventurier Malgré Lui',
        imageUrl: '/cards_visuals/lotr2c102.jpg',
        kind: 'FREE_PEOPLES',
        subType: 'COMPANION',
        signet: 'ARAGORN',
        twilightCost: 0,
        strength: 3,
        vitality: 4,
        culture: 'SHIRE',
        isUnique: true,
        gameText: DEFAULT_GAMETEXT,
    },
    {
        id: '1c10',
        title: 'Courage Nààààààain',
        imageUrl: '/cards_visuals/lotr1c10.webp',
        kind: 'FREE_PEOPLES',
        subType: 'CONDITION_CHARACTER',
        twilightCost: 0,
        culture: 'DWARVEN',
        isUnique: false,
        gameText:
            "Le détenteur doit être un Nain.\nQuand vous jouez cette situation, guérissez le détenteur jusqu'à 2 fois. Au début de chacun de vos tours, affaiblissez le détenteur.",
        loreText:
            '...un Nain va toujours, le fardeau fut-il deux fois plus lourd que lui...',
    },
    {
        id: '1c61',
        title: 'Chants du Royaume Béni',
        imageUrl: '/cards_visuals/lotr1c61.webp',
        kind: 'FREE_PEOPLES',
        subType: 'CONDITION_SUPPORT',
        twilightCost: 1,
        culture: 'ELVEN',
        isUnique: false,
        gameText: "Jouable dans votre aire de soutien.\nChaque fois que vous jouez un récit {CULTURE_ELVEN}, vous pouvez retirer un point-fardeau.",
        loreText:
            'Les Elfes semblent aimer la musique et la poésie autant que les Hobbits aiment la nourriture.',
    },
    {
        id: '1c299',
        title: 'Épée Hobbite',
        imageUrl: '/cards_visuals/lotr1c299.jpg',
        kind: 'FREE_PEOPLES',
        subType: 'POSSESSION_CHARACTER',
        twilightCost: 1,
        culture: 'SHIRE',
        isUnique: false,
        gameText: 'Le détenteur doit être un Hobbit.',
    },
    {
        id: '1r89',
        title: 'Aragorn',
        subtitle: 'Rôdeur du Nord',
        keyword: 'RANGER',
        race: 'MAN',
        imageUrl: '/cards_visuals/lotr1r89.jpg',
        kind: 'FREE_PEOPLES',
        subType: 'COMPANION',
        signet: 'GANDALF',
        twilightCost: 4,
        strength: 8,
        vitality: 4,
        culture: 'GONDOR',
        isUnique: true,
        gameText:
            "Manoeuvre: Affaiblissez Aragorn pour le rendre défenseur +1 jusqu'à la phase de ralliement",
        loreText:
            "Nous sommes des hommes solitaires, Rôdeurs des Terres Sauvages, chasseurs - mais toujours chasseurs des serviteurs de l'Ennemi...",
    },
    {
        id: '1r50',
        title: 'Legolas',
        subtitle: 'Vertefeuille',
        keyword: 'ARCHER',
        imageUrl: '/cards_visuals/lotr1r50.jpg',
        kind: 'FREE_PEOPLES',
        signet: 'FRODO',
        race: 'ELF',
        subType: 'COMPANION',
        twilightCost: 2,
        strength: 6,
        vitality: 3,
        culture: 'ELVEN',
        isUnique: true,
        gameText: DEFAULT_GAMETEXT,
    },
    {
        id: '1r13',
        title: 'Gimli',
        subtitle: 'Fils de Glóin',
        imageUrl: '/cards_visuals/lotr1r13.jpg',
        kind: 'FREE_PEOPLES',
        keyword: 'DAMAGE',
        signet: 'GANDALF',
        race: 'DWARF',
        subType: 'COMPANION',
        twilightCost: 2,
        strength: 6,
        vitality: 3,
        culture: 'DWARVEN',
        isUnique: true,
        gameText: '**Skirmish:** Exert Gimli to make him strength +2',
    },
    {
        id: '1r96',
        title: 'Boromir',
        subtitle: 'Seigneur du Gondor',
        imageUrl: '/cards_visuals/lotr1r96.jpg',
        kind: 'FREE_PEOPLES',
        signet: 'ARAGORN',
        race: 'MAN',
        subType: 'COMPANION',
        twilightCost: 3,
        strength: 7,
        vitality: 3,
        culture: 'GONDOR',
        isUnique: true,
        gameText: DEFAULT_GAMETEXT,
    },
];

export const SHADOW_DATABASE: CardType[] = [
    {
        id: '1r237',
        title: 'Le Roi-Sorcier',
        subtitle: "Seigneur d'Angmar",
        imageUrl: '/cards_visuals/lotr1r237.jpg',
        kind: 'SHADOW',
        race: 'NAZGUL',
        subType: 'MINION',
        roaming: 3,
        twilightCost: 8,
        strength: 14,
        vitality: 4,
        culture: 'RINGWRAITH',
        isUnique: true,
        gameText: DEFAULT_GAMETEXT,
    },
    {
        id: '3c69"',
        title: 'Saroumane',
        subtitle: "Serviteur de l'Oeil",
        imageUrl: '/cards_visuals/lotr3c69.jpg',
        kind: 'SHADOW',
        race: 'WIZARD',
        subType: 'MINION',
        roaming: 4,
        twilightCost: 4,
        strength: 8,
        vitality: 4,
        culture: 'ISENGARD',
        isUnique: true,
        gameText: DEFAULT_GAMETEXT,
    },
    {
        id: '1c191',
        title: 'Éclaireur de la Moria',
        imageUrl: '/cards_visuals/lotr1c191.jpg',
        kind: 'SHADOW',
        race: 'ORC',
        roaming: 4,
        subType: 'MINION',
        twilightCost: 1,
        strength: 5,
        vitality: 1,
        culture: 'MORIA',
        isUnique: false,
        gameText: DEFAULT_GAMETEXT,
    },
    {
        id: '1c271',
        title: 'Soldat Orque',
        imageUrl: '/cards_visuals/lotr1c271.jpg',
        kind: 'SHADOW',
        race: 'ORC',
        roaming: 6,
        subType: 'MINION',
        twilightCost: 2,
        strength: 7,
        vitality: 2,
        culture: 'SAURON',
        isUnique: false,
        gameText: DEFAULT_GAMETEXT,
    },
];

export const DUMMY_SITES_PLAYER_0: SiteCard[] = [
    {
        id: '11u227',
        name: "Berges de l'Anduin",
        twilightCost: 0,
        text: "River. Le total d'archerie des séides est de +2 pour chaque compagnon au delà de 4.",
        keyword: 'RIVER',
        ownerId: '0',
        imageUrl: '/cards_visuals/sites/lotr11u227.jpg'
    },
    {
        id: 'fsdfsdfsfsd',
        name: "Berges de l'Anduin",
        twilightCost: 0,
        text: "River. Le total d'archerie des séides est de +2 pour chaque compagnon au delà de 4.",
        keyword: 'RIVER',
        ownerId: '0',
        imageUrl: '/cards_visuals/sites/lotr11227.jpg'
    },
    {
        id: 'a',
        name: "Berges de l'Anduin",
        twilightCost: 0,
        text: "River. Le total d'archerie des séides est de +2 pour chaque compagnon au delà de 4.",
        keyword: 'RIVER',
        ownerId: '0',
        imageUrl: '/cards_visuals/sites/lotr11227.jpg'
    },
    {
        id: 'b',
        name: "Berges de l'Anduin",
        twilightCost: 0,
        text: "River. Le total d'archerie des séides est de +2 pour chaque compagnon au delà de 4.",
        keyword: 'RIVER',
        ownerId: '0',
        imageUrl: '/cards_visuals/sites/lotr11227.jpg'
    },
    {
        id: 'c',
        name: "Berges de l'Anduin",
        twilightCost: 0,
        text: "River. Le total d'archerie des séides est de +2 pour chaque compagnon au delà de 4.",
        keyword: 'RIVER',
        ownerId: '0',
        imageUrl: '/cards_visuals/sites/lotr11227.jpg'
    },
    {
        id: 'd',
        name: "Berges de l'Anduin",
        twilightCost: 0,
        text: "River. Le total d'archerie des séides est de +2 pour chaque compagnon au delà de 4.",
        keyword: 'RIVER',
        ownerId: '0',
        imageUrl: '/cards_visuals/sites/lotr11227.jpg'
    },
    {
        id: 'e',
        name: "Berges de l'Anduin",
        twilightCost: 0,
        text: "River. Le total d'archerie des séides est de +2 pour chaque compagnon au delà de 4.",
        keyword: 'RIVER',
        ownerId: '0',
        imageUrl: '/cards_visuals/sites/lotr11227.jpg'
    },
    {
        id: 'f',
        name: "Berges de l'Anduin",
        twilightCost: 0,
        text: "River. Le total d'archerie des séides est de +2 pour chaque compagnon au delà de 4.",
        keyword: 'RIVER',
        ownerId: '0',
        imageUrl: '/cards_visuals/sites/lotr11227.jpg'
    },
    {
        id: 'g',
        name: "Berges de l'Anduin",
        twilightCost: 0,
        text: "River. Le total d'archerie des séides est de +2 pour chaque compagnon au delà de 4.",
        keyword: 'RIVER',
        ownerId: '0',
        imageUrl: '/cards_visuals/sites/lotr11227.jpg'
    },

];
