import type { CardState, SiteCardState } from './types';

const DEFAULT_IMAGE = '/cards_visuals/lotr_default.jpg';
const DEFAULT_GAMETEXT =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.';
/*
Formatted Text :
    \n => Return
    ** my text ** => bold
*/

export const CARDS_DATABASE: CardState[] = [
    {
        id: '2c102',
        title: 'Frodon',
        subtitle: 'Aventurier Malgré Lui',
        imageUrl: '/cards_visuals/lotr2c102.jpg',
        kind: 'FREE_PEOPLES',
        type: 'COMPANION',
        race: 'HOBBIT',
        keywords: ['RING-BEARER'],
        resistance: 10,
        signet: 'ARAGORN',
        twilightCost: 0,
        strength: 3,
        vitality: 4,
        culture: 'SHIRE',
        isUnique: true,
        gameText:
            'Le coût de chaque artefact, possession et récit {CULTURE_SHIRE} joué sur Frodon est de -1.',
        loreText:
            "Je ne suis pas fait pour les quâtes périlleuses. Je voudrais bien n'avoir jamais vu l'Anneau! Pourquoi m'est-il venu? Pourquoi ai-je été choisi?",
    },
    {
        id: '1r1',
        title: "L'Anneau Unique",
        subtitle: "Fléau d'Isildur",
        kind: 'NONE',
        type: 'THE-ONE-RING',
        subtype: 'THE-ONE-RING',
        strength: 1,
        vitality: 1,
        culture: 'THE-ONE-RING',
        isUnique: true,
        gameText: "**Réponse : **Si le détenteur est sur le point de se faire blesser, il met l'Anneau unique jusqu'à la phase de ralliement.\nTant qu'il a l'Anneay Unique au doigt, chaque fois que le Porteur de l'Anneau est sur le point de se faire blesser, ajoutez plutôt 2 point-fardeau",
        loreText: "l'Anneau glissa de son doigt tandis qu'il nageait...",
    },
    {
        id: '1c10',
        title: 'Courage Nain',
        imageUrl: '/cards_visuals/lotr1c10.webp',
        kind: 'FREE_PEOPLES',
        type: 'CONDITION_CHARACTER',
        twilightCost: 0,
        culture: 'DWARVEN',
        isUnique: false,
        gameText:
            "Le détenteur doit être un Nain.\nQuand vous jouez cette situation, guérissez le détenteur jusqu'à 2 fois. Au début de chacun de vos tours, affaiblissez le détenteur.",
        loreText:
            '...un Nain va toujours, le fardeau fut-il deux fois plus lourd que lui...',
    },
    {
        id: '1c61',
        title: 'Chants du Royaume Béni',
        imageUrl: '/cards_visuals/lotr1c61.webp',
        kind: 'FREE_PEOPLES',
        type: 'CONDITION_SUPPORT',
        twilightCost: 1,
        culture: 'ELVEN',
        isUnique: false,
        gameText:
            'Jouable dans votre aire de soutien.\nChaque fois que vous jouez un récit {CULTURE_ELVEN}, vous pouvez retirer un point-fardeau.',
        loreText:
            'Les Elfes semblent aimer la musique et la poésie autant que les Hobbits aiment la nourriture.',
    },
    {
        id: '1c299',
        title: 'Épée Hobbite',
        imageUrl: '/cards_visuals/lotr1c299.jpg',
        kind: 'FREE_PEOPLES',
        type: 'POSSESSION_CHARACTER',
        subtype: 'HAND-WEAPON',
        strength: 2,
        twilightCost: 1,
        culture: 'SHIRE',
        isUnique: false,
        gameText: 'Le détenteur doit être un Hobbit.',
        loreText: 'Prenez ceci...',
    },
    {
        id: '1r45',
        title: 'Galadriel',
        subtitle: 'La Dame Blanche',
        race: 'ELF',
        imageUrl: '/cards_visuals/lotr1r45.webp',
        kind: 'FREE_PEOPLES',
        type: 'ALLY',
        resistance: 6,
        twilightCost: 3,
        strength: 3,
        vitality: 3,
        culture: 'ELVEN',
        isUnique: true,
        gameText:
            'Au début de chacun de vos tours, guérissez chaque allié dont la demeure est un site 6.\n**Compagnie:** Affaiblissez Galadriel pour jouer un elfe gratuitement.',
        loreText:
            "Il étaient très grands, la Dame non moins que le Seigneur; et ils étaient graves et beaux... et les cheveux de la Dame étaient d'or foncé...",
    },
    {
        id: '1r89',
        title: 'Aragorn',
        subtitle: 'Rôdeur du Nord',
        keywords: ['RANGER'],
        race: 'MAN',
        imageUrl: '/cards_visuals/lotr1r89.jpg',
        kind: 'FREE_PEOPLES',
        type: 'COMPANION',
        resistance: 6,
        signet: 'GANDALF',
        twilightCost: 4,
        strength: 8,
        vitality: 4,
        culture: 'GONDOR',
        isUnique: true,
        gameText:
            "**Manoeuvre:** Affaiblissez Aragorn pour le rendre **défenseur +1** jusqu'à la phase de ralliement",
        loreText:
            "Nous sommes des hommes solitaires, Rôdeurs des Terres Sauvages, chasseurs - mais toujours chasseurs des serviteurs de l'Ennemi...",
    },
    {
        id: '1r50',
        title: 'Legolas',
        subtitle: 'Vertefeuille',
        keywords: ['ARCHER'],
        imageUrl: '/cards_visuals/lotr1r50.jpg',
        kind: 'FREE_PEOPLES',
        isStartingMember: true,
        signet: 'FRODO',
        resistance: 6,
        race: 'ELF',
        type: 'COMPANION',
        twilightCost: 2,
        strength: 6,
        vitality: 3,
        culture: 'ELVEN',
        isUnique: true,
        gameText: DEFAULT_GAMETEXT,
    },
    {
        id: '1r13',
        title: 'Gimli',
        subtitle: 'Fils de Glóin',
        imageUrl: '/cards_visuals/lotr1r13.jpg',
        isStartingMember: true,
        kind: 'FREE_PEOPLES',
        keywords: ['DAMAGE'],
        signet: 'GANDALF',
        resistance: 6,
        race: 'DWARF',
        type: 'COMPANION',
        twilightCost: 2,
        strength: 6,
        vitality: 3,
        culture: 'DWARVEN',
        isUnique: true,
        gameText: '**Skirmish:** Exert Gimli to make him strength +2',
    },
    {
        id: '1r96',
        title: 'Boromir',
        subtitle: 'Seigneur du Gondor',
        imageUrl: '/cards_visuals/lotr1r96.jpg',
        kind: 'FREE_PEOPLES',
        signet: 'ARAGORN',
        resistance: 6,
        race: 'MAN',
        type: 'COMPANION',
        twilightCost: 3,
        strength: 7,
        vitality: 3,
        culture: 'GONDOR',
        isUnique: true,
        gameText: DEFAULT_GAMETEXT,
    },
    {
        id: '1r237',
        title: 'Le Roi-Sorcier',
        subtitle: "Seigneur d'Angmar",
        imageUrl: '/cards_visuals/lotr1r237.jpg',
        kind: 'SHADOW',
        race: 'NAZGUL',
        type: 'MINION',
        roaming: 3,
        twilightCost: 8,
        strength: 14,
        vitality: 4,
        culture: 'RINGWRAITH',
        isUnique: true,
        gameText: DEFAULT_GAMETEXT,
    },
    {
        id: '3c69"',
        title: 'Saroumane',
        subtitle: "Serviteur de l'Oeil",
        imageUrl: '/cards_visuals/lotr3c69.jpg',
        kind: 'SHADOW',
        race: 'WIZARD',
        type: 'MINION',
        roaming: 4,
        twilightCost: 4,
        strength: 8,
        vitality: 4,
        culture: 'ISENGARD',
        isUnique: true,
        gameText: DEFAULT_GAMETEXT,
    },
    {
        id: '1c191',
        title: 'Éclaireur de la Moria',
        imageUrl: '/cards_visuals/lotr1c191.jpg',
        kind: 'SHADOW',
        race: 'ORC',
        roaming: 4,
        type: 'MINION',
        twilightCost: 1,
        strength: 5,
        vitality: 1,
        culture: 'MORIA',
        isUnique: false,
        gameText: DEFAULT_GAMETEXT,
    },
    {
        id: '1c271',
        title: 'Soldat Orque',
        imageUrl: '/cards_visuals/lotr1c271.jpg',
        kind: 'SHADOW',
        race: 'ORC',
        roaming: 6,
        type: 'MINION',
        twilightCost: 2,
        strength: 7,
        vitality: 2,
        culture: 'SAURON',
        isUnique: false,
        gameText: DEFAULT_GAMETEXT,
    },
];

export const DUMMY_SITES_PLAYER_0: SiteCardState[] = [
    {
        id: '11u227',
        name: "Berges de l'Anduin",
        twilightCost: 0,
        gameText: "Le total d'archerie des séides est de +2 pour chaque compagnon au delà de 4.",
        keywords: ['RIVER'],
        ownerId: '0',
        imageUrl: '/cards_visuals/sites/lotr11u227.jpg',
    },
    {
        id: '11s234',
        name: "Les Pics d'Emyn Muil",
        twilightCost: 0,
        gameText: "Si ce site est dans la région 2 et que la compagnie le quitte pendant la phase de ralliement, blessez chaque compagnon.",
        keywords: ['MOUNTAIN'],
        ownerId: '0',
        imageUrl: '/cards_visuals/sites/lotr11s234.jpg',
    },
    {
        id: '12u194',
        name: "Champ de Bataille du Plateau",
        twilightCost: 2,
        gameText: "** Combat :** Affaiblissez votre Homme (sauf un Homme pugnace) pour qu'il inflige des **dégâts +1**.",
        keywords: ['PLAINS'],
        ownerId: '0',
        imageUrl: '/cards_visuals/sites/lotr12u194.jpg',
    },
    {
        id: '11s258',
        name: "Buttes de Scories",
        twilightCost: 1,
        gameText: "Chaque fois qu'un compagnon est tué, ajoutez un point-fardeau.",
        keywords: ['BATTLEGROUND'],
        ownerId: '0',
        imageUrl: '/cards_visuals/sites/lotr11s258.jpg',
    },
    {
        id: '11s243',
        name: "Harrowdale",
        twilightCost: 3,
        gameText: "Jusqu'à la phase de ralliement, chaque séide qui combat un compagnon {CULTURE_ROHAN} perd acharné et ne peut pas acquérir acharné.",
        keywords: ['PLAINS'],
        ownerId: '0',
        imageUrl: '/cards_visuals/sites/lotr11s243.jpg',
    },
    {
        id: '11s250',
        name: "Méandre du Nord",
        twilightCost: 3,
        gameText: "Le total d'archerie des séides est de -3.",
        keywords: ['RIVER'],
        ownerId: '0',
        imageUrl: '/cards_visuals/sites/lotr11s250.jpg',
    },
    {
        id: '11s262',
        name: "La Tour de Garde de Cirith Ungol",
        twilightCost: 1,
        gameText: "**Manoeuvre : **Affaiblissez votre séide {CULTURE_ORC} pour défausser une carte au hasard de la main du joueur des Peuples Libres.",
        keywords: ['MOUNTAIN'],
        ownerId: '0',
        imageUrl: '/cards_visuals/sites/lotr11s262.jpg',
    },
    {
        id: '11s239',
        name: "La Clairière de Fangorn",
        twilightCost: 0,
        gameText: "Quand la compagnie se déplace jusqu'à ce site, ajoutez {TWILIGHT_1} pour chaque arme des Peuples Libres.",
        keywords: ['FOREST'],
        ownerId: '0',
        imageUrl: '/cards_visuals/sites/lotr11s239.jpg',
    },
    {
        id: '13s192',
        name: "Les Grandes Portes",
        twilightCost: 0,
        gameText: "Tant qu'un joueur peut désigner plus de compagnons que de séides, chaque séide a +1 en force.",
        keywords: ['BATTLEGROUND'],
        ownerId: '0',
        imageUrl: '/cards_visuals/sites/lotr13s192.jpg',
    },
];
