import path from 'path';

export const CSV_PATH = path.join(process.cwd(), 'lotro_card_data.csv');
export const OUTPUT_CARDS_PATH = path.join(process.cwd(), 'data/cards.json');
export const OUTPUT_SITES_PATH = path.join(process.cwd(), 'data/sites.json');

export const FEMALE_TITLES = new Set([
    'Galadriel',
    'Éowyn',
    'Arwen',
    'Rosie Cotton',
    'Uruviel',
    'Goldberry',
]);

export const GAME_PHASES = new Set([
    'FELLOWSHIP',
    'SHADOW',
    'MANEUVER',
    'ARCHERY',
    'ASSIGNMENT',
    'SKIRMISH',
    'REGROUP',
    'RESPONSE',
]);

export const VALID_RACES = new Set([
    'BALROG',
    'CREATURE',
    'DWARF',
    'ELF',
    'ENT',
    'HOBBIT',
    'MAIA',
    'MAN',
    'NAZGÛL',
    'ORC',
    'SPIDER',
    'TROLL',
    'URUK-HAI',
    'WIZARD',
    'WRAITH',
]);

export const VALID_CULTURES = new Set([
    'DUNLAND',
    'DWARVEN',
    'ELVEN',
    'GANDALF',
    'GOLLUM',
    'GONDOR',
    'ISENGARD',
    'MEN',
    'MORIA',
    'ORC',
    'RAIDER',
    'WRAITH',
    'ROHAN',
    'SAURON',
    'SHIRE',
    'THE-ONE-RING',
    'URUK-HAI',
]);

export const VALID_KEYWORDS = new Set([
    'AID',
    'AMBUSH',
    'ARCHER',
    'BATTLEGROUND',
    'BESIEGER',
    'CORSAIR',
    'DAMAGE +1',
    'DAMAGE +2',
    'DAMAGE +3',
    'DAMAGE +4',
    'DEFENDER +1',
    'DEFENDER +2',
    'DEFENDER +3',
    'DEFENDER +4',
    'DWELLING',
    'EASTERLING',
    'ENDURING',
    'ENGINE',
    'FIERCE',
    'FOREST',
    'FORTIFICATION',
    'HUNTER 1',
    'HUNTER 2',
    'HUNTER 3',
    'HUNTER 4',
    'KNIGHT',
    'LURKER',
    'MACHINE',
    'MARSH',
    'MOUNTAIN',
    'MUSTER',
    'PIPEWEED',
    'PLAINS',
    'RANGER',
    'RING-BEARER',
    'RING-BOUND',
    'RIVER',
    'SEARCH',
    'SOUTHRON',
    'SPELL',
    'STEALTH',
    'TALE',
    'TENTACLE',
    'TOIL 1',
    'TOIL 2',
    'TOIL 3',
    'TRACKER',
    'TWILIGHT',
    'UNBOUND',
    'UNDERGROUND',
    'UNHASTY',
    'VALIANT',
    'VILLAGER',
    'WARG-RIDER',
    'WEATHER',
]);

export const VALID_TARGET_TYPES = new Set(['MINION', 'COMPANION', 'ALLY']);

export const SHADOW_CULTURES = [
    'ISENGARD',
    'MORIA',
    'SAURON',
    'WRAITH',
    'DUNLAND',
    'RAIDER',
    'MEN',
    'ORC',
    'URUK-HAI',
];
